version: '2'

services:
  mongo:
    container_name: ms_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"
  web:
    container_name: ms_web
    build: ./web
    command: node web.js
    volumes:
      - ./web:/app/web
    ports:
      - "1331:1331"
  user:
    container_name: ms_user
    build: ./user
    command: nodemon ./bin/www
    volumes:
      - ./user:/app/user
    ports:
      - "1337:1337"
    depends_on:
      - mongo
  nginx:
    container_name: ms_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user