version: '3'

services:
  mongo:
    container_name: ms_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"
  # web:
  #   container_name: ms_web
  #   build: ./web
  #   command: node web.js
  #   volumes:
  #     - ./web:/app/web
  #   ports:
  #     - "1331:1331"
  web:
    container_name: ms_web
    build: ./web
    # command: npm run deploy
    command: npm start
    volumes:
      - ./web:/app/web
    ports:
      - "5000:5000"
  user:
    container_name: ms_user
    build: ./user
    command: nodemon ./bin/www
    volumes:
      - ./user:/app/user
    ports:
      - "1337:1337"
    depends_on:
      - mongo
  # netdata:
  #   image: ms_netdata
  #   hostname: invesgram.com # set to fqdn of host
  #   ports:
  #     - 19999:19999
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    container_name: ms_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user
      - web