version: '3'

services:
  nginx:
    container_name: ms_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./local.conf:/etc/nginx/conf.d/local.conf
    depends_on:
      - user
      - web
      - news
  news:
    container_name: ms_news
    build: ./news
    command: nodemon ./bin/www;
    volumes:
      - ./news:/app/news
    ports:
      - "1336:1336"
    networks:
      - invesgramnet
    depends_on:
      - mongo
    links:
      - mongo:mongo
  web:
    container_name: ms_web
    command: npm start
    volumes:
      - ./web:/app/web
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - user
  user:
    container_name: ms_user
    build: ./user
    links:
      - mongo:mongo
    volumes:
      - ./user:/app/user
    ports:
      - "1337:1337"
    depends_on:
      - mongo
  mongo:
    container_name: ms_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"