version: '3'

services:
  mongo:
    container_name: ms_mongo
    image: mongo
    command: mongod --port 27017 --bind_ip_all
    environment: MONGO_INITDB_DATABASE = invesgram
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"
    networks:
      - invesgramnet
  user:
    container_name: ms_user
    build: ./user
    command: nodemon ./bin/www;
    links:
      - mongo:mongo
    volumes:
      - ./user:/app/user
    ports:
      - "1337:1337"
    depends_on:
      - mongo
    networks:
      - invesgramnet
  web:
    container_name: ms_web
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - user
    networks:
      - invesgramnet
  nginx:
    container_name: ms_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user
      - web
    networks:
      - invesgramnet
networks:
  invesgramnet: