version: '3'

services:
  mongo:
    container_name: ms_mongo
    image: mongo
    command: mongod --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/db:/data/db"
  user:
    container_name: ms_user
    build: ./user
    command: >
      /bin/bash -c "
        sleep 10;
        nodemon ./bin/www;
      "
    volumes:
      - ./user:/app/user
    ports:
      - "1337:1337"
    depends_on:
      - mongo
  web:
    container_name: ms_web
    command: npm start
    volumes:
      - ./web:/app/web
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - user
  nginx:
    container_name: ms_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user
      - web